### ISSUE TITLE
成员申请Old_Cat_LM

### ISSUE THREAD

**Issue by FuDujilm** [Infinity-Technology-Union/Audit#5]
Dear ITU,
`这是我第二次填写lssue，因为github好鸡儿坑，老子填了半小时没发出去。`
正版ID:Old_Cat_LM，称呼老猫。
自我介绍:生日:07/11/18，身高172㎝，体重172斤，性别♂，现居四川内江，有需要可以来人肉我，对生存期望可以，不错，朝气蓬勃的，我觉得可以出阅读理解了（但是我不会做，求求语文老师做个人）。性格说不来，反正不会抑郁，会喷QQ动态抑郁症患者(草，这么草，得了病不看医生)。不喜欢和外人说话 ，祖安人，因为语文成绩不好 摆不来龙门阵。会C++'Holle Wrold Program Writing和python。擅长搭永动机，土制别野，后勤。会在pilipili upload water video。
联系方式很多，哔哩哔哩:UID:382228406，QQ:2968136830，E-mail:cheyennemix@163.com，2968136830@163.com，fudujilm@gmail.com。钉钉:oldcatlm。微信:NM_FuDuJiLM

**Comment by shenjackyuanjie** [comment]
泪目
